### ISSUE TITLE
EPG Timezone Correction - No Effect

### ISSUE THREAD

**Issue by bharris401** [ardoviniandrea/ViniPlay#58]
The shows on the guide are showing off by +8 hours. I've changed the EPG Timezone Correction, but it has no effect on the times; they remain off by +8 hours.

I am using XML from EPG.pw to Xeteve to Viniplay.

**Comment by donchi40** [comment]
@bharris401 
Hi, I'm not sure if this will help you, but it's a suggestion... 
I had a similar issue and what I did was add the TZ to the environment in my yaml file... so I added:
    environment:
      - TZ=Pacific/Honolulu
Now my TV Guide is showing the correct time at the top of the page...

**Comment by donchi40** [comment]
@bharris401 
Sorry I couldn't help... I'm just learning Viniplay so I definitely don't have the answers...Here is what my TV Guide shows: It's currently 1148 AM over here...

<img width="1067" height="308" alt="Image" src="https://github.com/user-attachments/assets/ab00b332-e307-4b31-b679-f70ddc404419" />

**Comment by donchi40** [comment]
@bharris401 I guess I owe you an apology... After looking more into it, I'm seeing the same as you now... the time at the top matches the programs shown in the grid table... but what's actually playing is off... so like what you see, if the time at the top is current/correct, it shows a show with the current time, but when I click it, it shows something from earlier... 
So for example, using the screenshot above, It shows 1100AM at the top, and it shows "Live: NBA Basketball" should be on, but it would be showing "Gotta See It"... I haven't played around enough to see exactly how many hours it's off... At this time, I'm not sure if it Viniplay or the actual EPG I'm pulling in...

**Comment by donchi40** [comment]
Unfortunately, it appears to be my epg file... as I just checked about 10-15 channels, and most were actually correct, only a few were "off".

**Comment by ardoviniandrea** [comment]
hello @donchi40 and @bharris401 
I actually found few issues with the layout rendering of offset EPG in the TV Grid.
took me a while but I pushed a new dev image yesterday with an additional fix that finally resolved a long lasting issue on my end when the time bar was correct, but the program grid was not.
If you are able to pull the image and test it again I'd appreciate some feedback if it worked 🙏

**Comment by donchi40** [comment]
@ardoviniandrea I just pulled the latest dev and am checking it out now...  So far it looks good, but I haven't gone thru all of my playlist... however, the ones I checked looks like they are correct with the epgs... I'll post more info if I run into any issues... now to wait for @bharris401 to check his side

**Comment by bharris401** [comment]
I pulled the latest, but I'm still seeing the same issue. Adjusting the UTC offset changes the timebar, but the shows that are on now don't move, and the shows are off by 8 hours. I haven't had time to try another EPG yet, though, so it still could be EPW.pw's data.

**Comment by ardoviniandrea** [comment]
@bharris401 just to confirm, you should try with :dev not :latest 
Do you mind checking if you have the right image?

**Comment by bharris401** [comment]
My bad, I did not. I just grabbed dev (dev_0.11.1), and the shows are still 8 hours behind. I cleared the cache and tried in Incognito and saw the same.

**Comment by donchi40** [comment]
@bharris401 I know it's been a while but wanted to pass on another tip if you're still having a problem...
Can you shell into the container and run the date command to see if the container is getting the correct date/time/timezone?
Just in case:
                ``` docker exec -it viniplay bash  ```
then        ``` date ```
mine produces    Mon Jan  5 13:00:20 HST 2026
which is exact for my location...

**Comment by bharris401** [comment]
I get Mon Jan 5 20:00:37 EST 2026, which is correct for me.

**Comment by donchi40** [comment]
As another tip to try, since you're using xteve, have you looked at 
https://github.com/sparkison/m3u-editor 
It's an iptv editor/viewer that's like xteve but with additional features and it's also currently being updated/maintained by it's creator...
You can get either m3u or xtream output to use on your other devices, like ViniPlayer, plus it has a built-in viewer if you want to test if streams are working...

Also, here's another epg source you could try:
https://epgshare01.online/epgshare01/epg_ripper_ALL_SOURCES1.xml.gz

https://epgshare01.online/epgshare01/0_READ_ME_FIRST_AS_I_CONTAIN_VERY_HELPFUL_INFO.html

**Comment by bharris401** [comment]
I've installed m3u-editor and added epg.pw and epgshare. epgshare works just fine, so I'll stick with that. epg.pw still shows 8 hours off. If I go to their [site](https://epg.pw/last/469366.html?lang=en), say for WFTV, it shows the correct show at the correct time, but when I add it to m3u-editor, it goes back to being 8 hours off. I'll be sticking with epgshare for now, thanks!!!

**Comment by donchi40** [comment]
Glad it worked out... 
What I suggest is to use m3u-editor and create a few custom playlists, and then feed those custom playlists and the corresponding epgs to viniplay.  
please update and close this issue if you're satisfied that viniplay is now loading the epgs correctly.
